sec-need-time: 900 # какое время должен провести игрок на сервере, что бы смог писать в чат
time-actions:
  - '[MESSAGE] &b&lОШИБКА: &7Вы не отыграли на сервере &b15 минут!'
  - '[TITLE] &b&lОШИБКА:%nl&fВы должны поиграть &b15 минут!'
  - '[SOUND] ENTITY_VILLAGER_NO;6;1'
